#!/bin/bash
# po/update-pot.sh
#
# Regenerates po/temporal_explorer.pot by extracting translatable strings
# from ALL Rust sources automatically, syncs LINGUAS <-> .po files,
# and runs msgmerge on every existing .po file at the end.
#
# ────────────────────────────────────────────────────────────────────────────
# HOW IT WORKS
# ────────────────────────────────────────────────────────────────────────────
#
#  Step 1 — Rust source scan
#    Finds every src/**/*.rs file that contains gettext() calls and runs
#    xgettext -L C on them to produce po/temporal_explorer.pot directly.
#    Files without gettext() are skipped to avoid parser noise.
#
#  Step 2 — POTFILES.in regeneration
#    Rewrites po/POTFILES.in from the discovered file list.
#    Do not edit this file manually — it is always overwritten.
#
#  Step 3 — Header fixup
#    Writes the final po/temporal_explorer.pot with the correct
#    Project-Id-Version (read from Cargo.toml) and POT-Creation-Date.
#
#  Step 4 — Bidirectional LINGUAS <-> .po sync
#    • A .po file found in po/ without a matching LINGUAS entry
#      → entry is added to LINGUAS automatically.
#    • A language listed in LINGUAS without a corresponding .po file
#      → file is created via msginit automatically.
#    All .po files are then updated with msgmerge --update so new strings
#    are merged and obsolete strings are flagged.
#
# ────────────────────────────────────────────────────────────────────────────
# USAGE
# ────────────────────────────────────────────────────────────────────────────
#
#   cd <repo root>
#   bash po/update-pot.sh
#
#  Safe to run repeatedly — existing translations are never overwritten,
#  only merged. New strings get empty msgstr entries to be filled in.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.."
PO_DIR="$ROOT/po"
OUT="$PO_DIR/temporal_explorer.pot"
POTFILES="$PO_DIR/POTFILES.in"
LINGUAS_FILE="$PO_DIR/LINGUAS"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "=== Temporal Explorer — regenerating .pot ==="
echo ""

# ── 1. Discover and filter Rust files containing gettext() ───────────────────
echo "[1/4] Discovering Rust files (.rs with gettext())..."
mapfile -t RUST_FILES < <(
    find "$ROOT/src" -name "*.rs" -type f \
    | xargs grep -l 'gettext(' 2>/dev/null \
    | sort
)
echo "   → ${#RUST_FILES[@]} .rs files with gettext() found"

if [[ ${#RUST_FILES[@]} -eq 0 ]]; then
    echo "   ⚠ No .rs files with gettext() found — nothing to extract."
    exit 0
fi

PKG_VER=$(grep -m1 '^version' "$ROOT/Cargo.toml" | sed 's/.*= *"//;s/"//')

xgettext \
    --from-code=UTF-8 \
    --language=C \
    --keyword=gettext \
    --add-comments=translators \
    --package-name=temporal-explorer \
    --package-version="$PKG_VER" \
    --output="$TMP/rust.pot" \
    "${RUST_FILES[@]}" 2>/dev/null

COUNT=$(grep -c '^msgid ' "$TMP/rust.pot" 2>/dev/null || echo 0)
echo "   → rust.pot generated ($COUNT entries)"

# ── 2. Update POTFILES.in automatically ──────────────────────────────────────
echo "[2/4] Updating POTFILES.in..."
{
    echo "# Auto-generated by po/update-pot.sh — do not edit manually"
    echo ""
    for f in "${RUST_FILES[@]}"; do
        echo "${f#"$ROOT/"}"
    done
} > "$POTFILES"
echo "   → POTFILES.in updated with ${#RUST_FILES[@]} entries"

# ── 3. Fix header and write final .pot ────────────────────────────────────────
echo "[3/4] Writing $OUT..."
DATE=$(date +"%Y-%m-%d %H:%M%z")

sed \
    -e "s|^\"Project-Id-Version:.*|\"Project-Id-Version: temporal-explorer $PKG_VER\\\\n\"|" \
    -e "s|^\"POT-Creation-Date:.*|\"POT-Creation-Date: $DATE\\\\n\"|" \
    -e "s|^\"PO-Revision-Date:.*|\"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\\\\n\"|" \
    -e "s|^\"Last-Translator:.*|\"Last-Translator: FULL NAME <EMAIL@ADDRESS>\\\\n\"|" \
    -e "s|^\"Language-Team:.*|\"Language-Team: LANGUAGE <LL@li.org>\\\\n\"|" \
    -e "s|^\"Language:.*|\"Language: \\\\n\"|" \
    "$TMP/rust.pot" > "$OUT"

echo "   → $OUT written"

# ── 4. Sync LINGUAS <-> .po files ────────────────────────────────────────────
echo "[4/4] Syncing LINGUAS <-> .po files..."

declare -A LINGUAS_SET
while IFS= read -r lang || [[ -n "$lang" ]]; do
    lang="$(echo "$lang" | tr -d '[:space:]')"
    [[ -z "$lang" || "$lang" == \#* ]] && continue
    LINGUAS_SET["$lang"]=1
done < "$LINGUAS_FILE"

ADDED_TO_LINGUAS=()
CREATED_PO=()

for po_file in "$PO_DIR"/*.po; do
    [[ -f "$po_file" ]] || continue
    lang=$(basename "$po_file" .po)
    if [[ -z "${LINGUAS_SET[$lang]:-}" ]]; then
        echo "   + LINGUAS: adding '$lang' (.po file exists)"
        echo "$lang" >> "$LINGUAS_FILE"
        LINGUAS_SET["$lang"]=1
        ADDED_TO_LINGUAS+=("$lang")
    fi
done

for lang in "${!LINGUAS_SET[@]}"; do
    po_file="$PO_DIR/$lang.po"
    if [[ ! -f "$po_file" ]]; then
        echo "   + Creating $lang.po via msginit..."
        msginit \
            --input="$OUT" \
            --locale="$lang" \
            --output="$po_file" \
            --no-translator \
            2>/dev/null || true
        if [[ -f "$po_file" ]]; then
            ENTRY_COUNT=$(grep -c '^msgid ' "$po_file" 2>/dev/null || echo 0)
            echo "   → $lang.po created ($ENTRY_COUNT entries)"
            CREATED_PO+=("$lang")
        else
            echo "   ⚠ msginit failed for '$lang' — is the locale installed?"
        fi
    fi
done

sort -u "$LINGUAS_FILE" > "$TMP/linguas_sorted"
mv "$TMP/linguas_sorted" "$LINGUAS_FILE"

[[ ${#ADDED_TO_LINGUAS[@]} -gt 0 ]] && echo "   → Added to LINGUAS: ${ADDED_TO_LINGUAS[*]}"
[[ ${#CREATED_PO[@]}       -gt 0 ]] && echo "   → .po files created: ${CREATED_PO[*]}"
[[ ${#ADDED_TO_LINGUAS[@]} -eq 0 && ${#CREATED_PO[@]} -eq 0 ]] && \
    echo "   → LINGUAS and .po files are already in sync"

echo ""
echo "✓ Generated: $OUT"
echo "✓ Total entries: $COUNT"
echo "✓ Version: temporal-explorer $PKG_VER"
echo "✓ Languages: $(tr '\n' ' ' < "$LINGUAS_FILE" | xargs)"

# ── Update ALL .po files (always) ────────────────────────────────────────────
echo ""
echo "=== Updating all .po files with msgmerge ==="
for po in "$PO_DIR"/*.po; do
    [[ -f "$po" ]] || continue
    lang=$(basename "$po" .po)
    printf "  → %-14s" "$lang.po"
    msgmerge --quiet --update --backup=none "$po" "$OUT"
    UNTRANSLATED=$(grep -c '^msgstr ""' "$po" 2>/dev/null || echo 0)
    TOTAL_ENTRIES=$(grep -c '^msgid '   "$po" 2>/dev/null || echo 0)
    echo " ($UNTRANSLATED/$TOTAL_ENTRIES untranslated)"
done
echo "✓ All .po files updated!"